name: R_line

on:
  workflow_dispatch: 
#   schedule:
#     - cron:  '0 10 * * *'

jobs:
  run_r_script:
    runs-on: ubuntu-latest
    
    steps:
      #- uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.0'
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "readr", "ggplot2"))
          remotes::install_deps(dependencies = TRUE)
          #install.packages(c( "rstan", "gridExtra", "incidence", "magrittr", "readr", "knitr", "dplyr","EpiNow2"))
        shell: sudo Rscript {0}
      - name: Run R Script
        run: Rscript ./Rt_calcs.R
