name: R_line

on:
  workflow_dispatch: 
  schedule:
    - cron:  '0 10 * * *'

jobs:
  run_r_script:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("EpiNow2", "rstan", "ggplot2", "gridExtra", "incidence", "magrittr", "readr", "knitr", "dplyr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Run R Script
        shell: Rscript ./Rt_calcs.R
