name: R_line

on:
  workflow_dispatch: 
#   schedule:
#     - cron:  '0 10 * * *'

jobs:
  run_r_script:
    runs-on: macos-latest
    
    steps:
      #- uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.0'
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          install.packages(c( "rstan", "gridExtra", "incidence", "magrittr", "readr", "knitr", "dplyr","EpiNow2"))
        shell: Rscript {0}
      - name: Run R Script
        run: Rscript ./Rt_calcs.R
