name: R_proc

on:
  workflow_dispatch: 
  schedule:
    - cron:  '0 10 * * *'

jobs:
  setup_run_r:
    runs-on: ubuntu-18.04
    env:
      PDF_SOURCE: 'http://stopcoronavirus.mcgm.gov.in/assets/docs/Dashboard.pdf'
      PDF_FILE_PATH: '/tmp/stopcovid-dashboard'
      CRAN_REPO: 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest'

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.0'
      - name: update apt-get
        run: sudo apt-get update -y
      - name: install v8
        run: sudo apt-get install libv8-dev libcurl4-openssl-dev  -y 
      - name: Install remotes
        run: |
          install.packages("remotes", repos = c("CRAN" = Sys.getenv("CRAN_REPO")))
        shell: Rscript {0}
      - name: Install Rstan
        run: |
          install.packages("rstan")
        shell: Rscript {0}
      - name: Install Epinow2
        run: |
          install.packages("EpiNow2")
        shell: Rscript {0}
      - name: Install deps
        run: |
          install.packages("drat")
          drat:::add("epiforecasts")
          install.packages("ggplot2")
          install.packages("gridExtra")
          install.packages("incidence")
          install.packages("magrittr")
          install.packages("readr")
          install.packages("knitr")
          install.packages("dplyr")
          install.packages("EpiEstim")
        shell: Rscript {0}
      - name: Run R script
        run: Rscript  Rt_calcs.R
      
      - uses: actions/upload-artifact@v2
        with:
          name: csv
          path: v1/r_out
      - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git stash save -u -a
            git fetch origin gh-pages
            git checkout gh-pages
            git pull --no-edit origin gh-pages
            git stash apply
            git add v1/*
            git commit -m "pushing result csv"
            git pull --no-edit origin gh-pages
            git push
        
