name: R_line

on:
  workflow_dispatch: 
#   schedule:
#     - cron:  '0 10 * * *'

jobs:
  run_r_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          export_default_credentials: true
      - run: gcloud info
